version: '2'

services:
  database:
    container_name: database-drupal
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    ports:
      - '4307:3306'
    volumes:
      - ./mysql:/var/lib/mysql

  php:
    container_name: php-drupal
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/html
    depends_on:
      - database

  nginx:
    container_name: nginx-drupal
    image: nginx:stable-alpine
    ports:
      - '8081:80'
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
